/*
  App.tsx
  =======
  Composes the whole page. This is the ONLY file that imports the
  section components. Agents C, D, E: do not edit this file, and do not
  import your section anywhere except here (it is already wired up).
  If a section needs a new prop, that is a scope violation, resolve it
  inside the section's own file, not by changing this composition.

  Fixed section order (locked by CONTRACT.md section 4/6):
    SiteNav -> Overview -> PriceFinding -> ImageFinding ->
    CategoryFinding -> Gallery -> SiteFooter

  Each section owns its own stable anchor id (set inside the section via
  SectionShell): overview, price, images, categories, gallery. SiteNav's
  scroll-spy targets those ids.
*/
import { SiteNav } from "./components/SiteNav";
import { SiteFooter } from "./components/SiteFooter";
import { Overview } from "./sections/Overview";
import { PriceFinding } from "./sections/PriceFinding";
import { ImageFinding } from "./sections/ImageFinding";
import { CategoryFinding } from "./sections/CategoryFinding";
import { Gallery } from "./sections/Gallery";

function App() {
  return (
    <>
      <SiteNav />
      <main>
        <Overview />
        <PriceFinding />
        <ImageFinding />
        <CategoryFinding />
        <Gallery />
      </main>
      <SiteFooter />
    </>
  );
}

export default App;
