/*
  findings.d.ts
  =============
  Type contract for `dashboard/src/data/findings.json` (generated by
  Agent A's `prepare_dashboard_data.py`, matching CONTRACT.md section 5
  exactly). This is the API every section component codes against.
  Import types from here, never redeclare a shape inline in a section.

  Every field below is REQUIRED unless its type explicitly includes
  `| null` (Agent A's contract guarantees the shape; there are no
  optional keys in this schema). `string | null` means "present, but
  may legitimately be null" (for example, an outlier with no resolvable
  image), which is different from an optional key that might be absent
  entirely: there are no absent keys here, only present-but-null ones.
*/

export interface FindingsSource {
  raw_csv: string;
  cleaner: string;
}

export interface FindingsPipeline {
  rows_in: number;
  rows_after_price_filter: number;
  product_type_filled: number;
  image_src_filled: number;
  rows_out: number;
}

export interface TopCategoryCount {
  product_type: string;
  count: number;
}

export interface FindingsOverview {
  total_products: number;
  distinct_handles: number;
  mean_price: number;
  median_price: number;
  min_price: number;
  max_price: number;
  product_types_raw: number;
  product_types_normalized: number;
  /** Top 10, already sorted by count descending. */
  top_categories: TopCategoryCount[];
}

export interface PriceHistogramBin {
  bin_start: number;
  bin_end: number;
  count: number;
}

export interface PriceOutlier {
  handle: string;
  title: string;
  variant_title: string;
  sku: string;
  product_type: string;
  price: number;
  /** First image URL for this SKU, or null if unresolved. */
  image: string | null;
}

export interface FindingsPrice {
  outlier_threshold: number;
  outlier_count: number;
  outlier_price: number;
  /** 0-1 fraction is NOT guaranteed; treat as already a percentage-scale
   *  number per CONTRACT.md's example (e.g. 0.03 meaning 0.03%). Format
   *  with lib/format.ts's percent formatter, do not assume a 0-1 range. */
  outlier_pct_of_total: number;
  multiple_of_mean: number;
  distinct_products: number;
  sizes_per_product: number;
  /** $5 bins from 0 to 100, plus one final overflow bin. */
  histogram: PriceHistogramBin[];
  /** ~700 prices, random sample (seed=42), EXCLUDING the 12 outliers. */
  strip_sample: number[];
  /** All 12 outlier rows. */
  outliers: PriceOutlier[];
}

export type ImageTierKey =
  | "same_handle"
  | "same_title_type"
  | "similar_title_token"
  | "unresolved";

export interface ImageTier {
  key: ImageTierKey;
  label: string;
  rule: string;
  products: number;
  remaining_after: number;
}

export interface UnresolvedImageRow {
  handle: string;
  title: string;
  product_type: string;
  price: number;
}

/**
 * The TRUE origin of every filled photo, as opposed to what `tiers`
 * reports. `_greedy_image_filler` mutates the frame while iterating, so a
 * tier-1 hit means "the loop already passed through this handle", not
 * "a genuine sibling was found". These fields are what the image section
 * actually narrates; `tiers` is kept only because the published Power BI
 * tables are built from it.
 */
export interface ImageProvenance {
  /** Rows that borrowed from a genuine same-product sibling. It is 0. */
  genuine_sibling_resolutions: number;
  /** Tier 3 token guesses written into the frame during the loop. */
  token_guess_seeds: number;
  /** Rows that later matched tier 1 against one of those guesses. */
  propagated_from_guesses: number;
  /** Distinct rows with a real photo that acted as donors. */
  distinct_clean_donor_rows: number;
  /** True when the tier split depends on input row order. */
  order_dependent: boolean;
}

export interface FindingsImages {
  initial_missing: number;
  resolved: number;
  resolved_pct: number;
  unresolved: number;
  /** Ordered funnel: same_handle -> same_title_type -> similar_title_token -> unresolved. */
  tiers: ImageTier[];
  /** Where the filled photos genuinely came from. Drives the narrative. */
  provenance: ImageProvenance;
  /** The 7 still-missing rows. */
  unresolved_rows: UnresolvedImageRow[];
}

export interface CategoryVariant {
  raw: string;
  count: number;
}

export interface CategoryPair {
  norm: string;
  total: number;
  /** Every distinct raw spelling collapsing into this normalized key. */
  variants: CategoryVariant[];
}

export interface CategoryRankRaw {
  label: string;
  count: number;
  rank: number;
}

export interface CategoryRankNormalized {
  label: string;
  count: number;
  rank: number;
  /** Rank position change vs the raw (un-normalized) top 10. */
  rank_delta: number;
}

export interface FindingsCategories {
  raw_unique: number;
  normalized_unique: number;
  /** Number of normalized keys with more than one raw spelling. */
  collapsed_groups: number;
  /** Every fragmented group, sorted by total descending. */
  pairs: CategoryPair[];
  top10_raw: CategoryRankRaw[];
  top10_normalized: CategoryRankNormalized[];
}

export interface GalleryItem {
  handle: string;
  title: string;
  product_type: string;
  price: number;
  /** Single https URL, always present for gallery items. */
  image: string;
  is_outlier: boolean;
  /** Short English note, present ONLY on the 2 outlier products. */
  note: string | null;
  /**
   * True when this row's photo was borrowed by the image filler because
   * the product had none of its own, so the picture shows a DIFFERENT
   * product. The gallery must disclose this rather than imply the photo
   * is the product's own.
   */
  image_is_borrowed: boolean;
}

export interface Findings {
  generated_at: string;
  source: FindingsSource;
  pipeline: FindingsPipeline;
  overview: FindingsOverview;
  price: FindingsPrice;
  images: FindingsImages;
  categories: FindingsCategories;
  /** 48 cards. */
  gallery: GalleryItem[];
}
