/*
  findings.ts
  ===========
  The ONLY place in the app that touches `data/findings.json` directly.
  Section components (Overview, PriceFinding, ImageFinding,
  CategoryFinding, Gallery, GalleryCard) must import `findings` from
  here, never `import ... from "../data/findings.json"` themselves.
  That keeps the JSON->TS boundary in one file, so if Agent A's
  generator shape ever needs a shim, it happens once, here.

  NOTE for review: `../data/findings.json` is generated by Agent A's
  `prepare_dashboard_data.py` and is intentionally NOT created by this
  file or by Agent B. Until that file exists, this module (and anything
  importing it) will fail to typecheck/build with "Cannot find module
  '../data/findings.json'". That is expected, not a bug in this file.
*/
import raw from "../data/findings.json";
import type { Findings } from "../data/findings";

// The JSON import's inferred literal shape and the hand-written
// `Findings` interface are structurally close but not guaranteed to be
// assignable in one step (e.g. `ImageTier["key"]` is a 4-value union in
// `Findings`, but a generic JSON import infers a wider `string`). Route
// through `unknown` deliberately: Agent A's generator is contractually
// bound to CONTRACT.md section 5, so this is a type-level bridge, not a
// runtime risk.
export const findings = raw as unknown as Findings;
